### ISSUE TITLE
Field labeling: Medicine amount vs. Dose

### ISSUE THREAD

**Issue by uli-on** [pewaru-333/HomeMedkit-App#4]
When setting up a timer, there's probably a mistake in the label name of "medicine amount", at least for my understanding. It should probably be named "dose", because the total amount of pills makes no sense at this point of time.

EDIT: Oh, and the label should be "dose" , not "doze".

**Comment by pewaru-333** [comment]
Thank you. Field "Medicine amount" means how much pills/tablets/capsules you need to intake. Fiels "Dose" means a full weight or volume of a medicine. For example, "250 mg" or "10 mL". This was done due to the fact that when receiving information about the medicine, when scanning the DataMatrix, these two fields are combined into one, which would make it very difficult to "pull out" the desired value and strings.

Translation will be fix in 1.0.3

**Comment by uli-on** [comment]
So I really misinterpreted the label translation. And finally also (part of) the app's task. Or do you have plans to also remind the users about medicines running low?

**Comment by uli-on** [comment]
There are things that don't click the way I expect the app to work: Why do I have to enter the value for medicine amount a second time when setting up a reminder?

**Comment by pewaru-333** [comment]
When you fill the "Medicine amount" field in the intake screen, this amount will be automatically subtracted from the remaining amount of the medicine.

**Comment by uli-on** [comment]
Sorry, but all this still doesn't make "click" in my head. I shouldn't feel demanded using such an app. It should be self-explanatory and guide me.

**Comment by pewaru-333** [comment]
> Sorry, but all this still doesn't make "click" in my head. I shouldn't feel demanded using such an app. It should be self-explanatory and guide me.

Good evening. Please check and rate a new intake screen.
